### ISSUE TITLE
Ability to change cookie name

### ISSUE THREAD

**Issue by derimagia** [Alimir/wp-ulike#1]
Trying to get this work on Pantheon but because pantheon uses Varnish this plugin breaks. Pantheon's VCL file is here: https://pantheon.io/docs/articles/sites/varnish/caching-advancedtopics/

If we had the ability to change the cookie name (filter?) that would be a work around so that I can prefix it with "wp-".

**Comment by djm56** [comment]
In the wp-ulike.php there are two sections to change the cookie name, I have tested with new names and it seems to work. Line 38
`$data = array(
			"id" 		=> $post_ID,				//Post ID
			"user_id" 	=> $return_userID,			//User ID (if the user is guest, we save ip as user_id with "ip2long" function)
			"user_ip" 	=> $wp_user_IP,				//User IP
			"get_like" 	=> $get_like,				//Number Of Likes
			"method" 	=> 'likeThis',				//JavaScript method
			"setting" 	=> 'wp_ulike_posts',		//Setting Key
			"type" 		=> 'post',					//Function type (post/process)
			"table" 	=> 'ulike',					//posts table
			"column" 	=> 'post_id',				//ulike table column name			
			"key" 		=> '_liked',				//meta key
			"cookie" 	=> 'liked-'					//Cookie Name
		);	`

and this section in the same file. Line 325
`if($post_type == 'likeThis'){
			$get_meta_data 	= get_post_meta($post_ID, '_liked', true);
			$setting_key	= 'wp_ulike_posts';
			$table_name		= 'ulike';
			$column_name	= 'post_id';
			$meta_key		= '_liked';
			$cookie_name	= 'liked-';
		}`

Maybe these fields can be put into the database wp-options, and then they are very easy to change.
I hop this helps

**Comment by Derimagia** [comment]
Thanks for the info. Hope it helps someone

I knew how to change it, but I rarely like to patch a contrib plugin. I highly recommend changing it though so services like pantheon works, or like you said making it a config option.
