### ISSUE TITLE
Ajax callback not works for some reason

### ISSUE THREAD

**Issue by amindiary** [Alimir/wp-ulike#10]
Hi, Im using your plugin, that was working fine but not sure why stopped working, disabled plugins but still not works, actually it kinda works, but loading not disappear till I refresh page.
Sent you email about this too, if its possible can you guide me how solve it?
Thank you for your great plugin BTW.

http://testhosting.co.uk/agespace/topic/test-topic-here/

**Comment by Alimir** [comment]
Hi @amindiary 
Please check the latest version of wp ulike. (Currently V2.8)
