### ISSUE TITLE
Button not accessible

### ISSUE THREAD

**Issue by pixelstrolch** [Alimir/wp-ulike#30]
Hi there, thanks for this nice looking plugin.

I found out that the like button is not accessible with the keyboard because of the missing `href` attribute. Moreover, the semantically better way would be to use the `<button>` element instead of `<a>`.

**Comment by Alimir** [comment]
Thanks @pixelstrolch 
I will make an update for tonight ;)

**Comment by pixelstrolch** [comment]
Thanks @Alimir for the update. The button can now be accessed with the keyboard. However, in most cases the focus probably wont be visible because of 
```
.wpulike .wp_ulike_btn:active, 
.wpulike .wp_ulike_btn:focus, 
.wpulike .wp_ulike_btn:hover {
    outline: 0;
}
```
I’d recommend to remove the second focus line. Therefore, it’d be up to the theme or the browser styles to show where the user is located.
