### ISSUE TITLE
Some parts are missing the translation placeholder

### ISSUE THREAD

**Issue by FunnyUncle** [Alimir/wp-ulike#32]
The text shown below shows up on the news feed of buddypress when someone liked a post.

Problem: it is not possible to translate the string because the __() is missing. Can this please be added, its only a matter of seconds to include.

Thank you!

file: 
- general-functions.php 
- general-hooks.php

string:
(So far, This post has <span class="badge">%POST_COUNT%</span> likes)

**Comment by Alimir** [comment]
Hi @FunnyUncle 
This section does not need to be translated and can be modified in the plugin settings :100:
