### ISSUE TITLE
Adds the like count at the end of post excerpt

### ISSUE THREAD

**Issue by shamimmoeen** [Alimir/wp-ulike#52]
If the post content is not enough long then when getting the post excerpt the like count is added at the end.

![wpulike-issue](https://user-images.githubusercontent.com/7997852/59562772-926f5a80-9052-11e9-863f-9d0342d2da19.png)

**Comment by remkus** [comment]
Any word on this how we can remove this?

**Comment by Mierscheid** [comment]
I have the same issue! 
I love WP ULike very, very much, but this looks ugly. :-(

**Comment by cwhatley** [comment]
One way to solve this problem would be to move the like count to a `data-like-count` attribute of the tag instead of as text and have some JS modify the dom based on that attribute. Then the counts won't show in the excerpts.
