### ISSUE TITLE
Start Like button with a minimum number != 0. And new post automattic likes plus 1 than the most liked post

### ISSUE THREAD

**Issue by venturaEffect** [Alimir/wp-ulike#66]
Hi friends,

First of all congrats for the plugin...

Have done some customisations taking code from the readme. Removed 0 and plus. Problem. Got a site issue and could not solved. No other solution than remove these code...

Now I want that LIKE button starts with a minimum number different than 0. Example: 4.

Also want that when a new post is posted it gets the same likes than the most liked plus 1 more.

Is all this possible? Any suggestion will be highly appreciated.

Wish you a great day

**Comment by Alimir** [comment]
Hey @venturaEffect 
This feature is available in the pro version.
