### ISSUE TITLE
How to disable aggregateRating schema metadata?

### ISSUE THREAD

**Issue by ranjan-purbey** [Alimir/wp-ulike#68]
I installed WP ULike plugin on my local fresh installation of WP. I followed the steps to remove all schema data. But I still see a `aggregateRating` field which throws errors on Google structured data testing tool. 
![image](https://user-images.githubusercontent.com/6953187/71067780-2e615680-219b-11ea-859c-ef62bee65c99.png)

Any way to remove it?

**Comment by Alimir** [comment]
Hi @ranjan-purbey 
Go to "WP ULike > Settings > Posts' & Disable '*Google Rich Snippets' options.

**Comment by ranjan-purbey** [comment]
Thanks! That solved it. I don't know how I missed the option in settings. Closing.
