### ISSUE TITLE
Performance issue with in 4.x because of switch to custom database table

### ISSUE THREAD

**Issue by nturbanov** [Alimir/wp-ulike#70]
Hi there,

It looks like when you switched from using post meta to your custom database table you subsequently created some performance issues as you've almost completely sidestepped WordPress's built-in caching mechanisms.

Post meta automatically uses the built-in object caching, and thus any persistent caching (ie. Redis etc.) hooking into the built-in object offers great benefits in more demanding cases.

By using your custom table and subsequently custom database queries, you completely miss this advantage and thus possibly execute a whole lot of unnecessary db queries.

In the simplest form you should at least utilize `wp_cache_set()`/`wp_cache_add()` and `wp_cache_get()` with your custom queries. 

[You actually already do once](https://github.com/Alimir/wp-ulike/blob/5b5accac5abf8fce23549376715cb64c1583ab13/inc/general-functions.php#L526) but I'm not sure why you haven't in all the different queries related to like count data.

I know caching is always harder than it seems and I would actually appreciate even more robust configurable caching options, but this seems like a low hanging fruit.

**Comment by Alimir** [comment]
Hi @nturbanov 
Thank you for pointing out this issue. We already had some problems with cache, so we skipped it.
But today I seriously considered it and added some commits to solve the problem. I think it will be much more optimized now. :)))
