### ISSUE TITLE
"Search an Icon" field is shown in *every* admin page footer

### ISSUE THREAD

**Issue by joostdekeijzer** [Alimir/wp-ulike#71]
The "Add Icon" label with "Search an Icon..." field is shown on every admin page. See screendump.

Seems to originate from https://github.com/Alimir/wp-ulike/blob/master/admin/settings/functions/actions.php#L200

Not sure why it's there...

![Screenshot 2020-02-25 at 10 04 55](https://user-images.githubusercontent.com/216672/75231972-b2951300-57b6-11ea-8dfc-d2132cc57393.png)

**Comment by joostdekeijzer** [comment]
Did more test: v4.1.6 does not have this issue, v4.1.7 does.

**Comment by joostdekeijzer** [comment]
Originates from b7442cf change

**Comment by Alimir** [comment]
@joostdekeijzer Thanks for report. I'll fix this for tomorrow update.
