### ISSUE TITLE
Add autocomplete="off" to front end checkboxes to disable Firefox's automatic state caching

### ISSUE THREAD

**Issue by nturbanov** [Alimir/wp-ulike#76]
You use hidden checkboxes on the front end to set the Like state. When liking is **enabled only for logged in users** and a user is **not logged in**, clicking the like button still changes its state and the icon changes color (the heart goes red in my case).

In Firefox, refreshing the page does not reset the like state - it is still shown as if I have liked the article. This is obviously incorrect, as non-logged in users cannot like articles (with these settings).

This is because [Firefox caches the state of `checked` for checkboxes.](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)

This can be disabled by adding `autocomplete="off"` to checkboxes. There are no drawbacks as this is the default behavior for other browsers and there's no need to support autocomplete for these hidden checkboxes anyway.

**Comment by Alimir** [comment]
@nturbanov Thanks to your report, this problem only existed in one of the templates and I will fix it in the next update. :)
