### ISSUE TITLE
4.5.1 breaks Buddyboss activity stream

### ISSUE THREAD

**Issue by contemplate** [Alimir/wp-ulike#81]
The new lines added here seem to break our Buddyboss activity stream on the platform/theme:
https://github.com/Alimir/wp-ulike/blob/2b564d5ac8bef7113b30864e358e65d39b7cab76/assets/js/wp-ulike.js#L1025-L1028

We get a JS error which then prevent the activities from loading:
Uncaught ReferenceError: ulp_main_elements is not defined

We had to roll back to 4.5.0

**Comment by Alimir** [comment]
@contemplate Thanks, The problem has been solved!
