### ISSUE TITLE
undefined function ulf_get_google_fonts()

### ISSUE THREAD

**Issue by Brain8torm** [Alimir/wp-ulike#86]
I can't install plugin. On settings pages - error

Fatal error: Uncaught Error: Call to undefined function ulf_get_google_fonts() in \wp-content\plugins\wp-ulike\admin\settings\fields\typography\typography.php:389

WP ULike - 4.5.6 -latest from Wordpress.org
Wordpress - 5.8.1

**Comment by sanzeeb3** [comment]
The function is defined right in `fields\typography\google-fonts.php`, I think the file itself isn't included for you. Do you maybe have a `google-fonts.php` file within your theme?

**Comment by Brain8torm** [comment]
The error starts with version 4.4.7, previous versions do not have such an error. File fields\typography\google-fonts.php there is, there is no similar file in  theme.

**Comment by sanzeeb3** [comment]
@Brain8torm I think that there's an issue including the file `google-fonts.php` probably because you've backslash `\` as a directory separator, but I'm not sure.

**Comment by Brain8torm** [comment]
The error was detected on a local server on Windows, where the directory separator is a backslash. There is no such error on linux hosting.

**Comment by Alimir** [comment]
This issue has been fixed inside the new version.
